spring:
  datasource:
    url: ${UMS_DB_URL:jdbc:mysql://ums-db:3306/microtwitter_ums}
    username: ${UMS_DB_USERNAME:root}
    password: ${UMS_DB_PASSWORD:root123}

server:
  port: ${SERVER_PORT:8081}
